apiVersion: auth.openkube.io/v1alpha1
kind: User
metadata:
  name: bob-developer
spec:
  auth:
    type: x509
    ttl: 720h
  roles:
    - namespace: dev
      existingClusterRole: kubeuser-developer
  clusterRoles:
    - existingClusterRole: kubeuser-viewer
