apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubeuser.fullname" . }}-controller-manager
  namespace: {{ include "kubeuser.namespace" . }}
  labels:
    {{- include "kubeuser.managerLabels" . | nindent 4 }}
  {{- with .Values.podLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubeuser.managerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "kubeuser.managerSelectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubeuser.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: manager
        image: {{ include "kubeuser.image" . }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command:
        - /manager
        args:
        {{- range .Values.manager.args }}
        - {{ . }}
        {{- end }}
        env:
        - name: WEBHOOK_SERVICE_NAME
          value: {{ include "kubeuser.fullname" . }}-webhook-service
        - name: KUBEUSER_NAMESPACE
          value: {{ include "kubeuser.namespace" . }}
        {{- with .Values.env }}
        {{- range $key, $value := . }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        ports:
        - containerPort: 9443
          name: webhook-server
          protocol: TCP
        - containerPort: 8081
          name: health
          protocol: TCP
        {{- if .Values.metrics.enabled }}
        - containerPort: {{ .Values.metrics.service.port }}
          name: metrics
          protocol: TCP
        {{- end }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 12 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 12 }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - mountPath: {{ .Values.webhook.certPath }}
          name: webhook-certs
        - mountPath: /tmp
          name: tmp-dir
      volumes:
      - name: webhook-certs
        secret:
          secretName: {{ include "kubeuser.fullname" . }}-webhook-certs
          defaultMode: 420
      - name: tmp-dir
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10