{{- if .Values.webhook.enabled }}
---
# ValidatingWebhookConfiguration with cert-manager CA injection
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kubeuser.fullname" . }}-validating-webhook-configuration
  labels:
    {{- include "kubeuser.labels" . | nindent 4 }}
  annotations:
    # cert-manager will inject the CA bundle automatically
    cert-manager.io/inject-ca-from: {{ include "kubeuser.namespace" . }}/{{ include "kubeuser.fullname" . }}-webhook-cert
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: {{ include "kubeuser.fullname" . }}-webhook-service
      namespace: {{ include "kubeuser.namespace" . }}
      path: /validate-auth-openkube-io-v1alpha1-user
    # caBundle will be injected automatically by cert-manager
  failurePolicy: {{ .Values.webhook.failurePolicy | default "Fail" }}
  name: user.auth.openkube.io
  rules:
  - apiGroups:
    - auth.openkube.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - users
  sideEffects: None
{{- end }}
